### PR TITLE
Delete moved CronJobSource.

### PR DESCRIPTION
**Pull request by n3wscott**
Follow-up to https://github.com/knative/eventing/pull/1092

## Proposed Changes

  * Delete moved CronJobSource

**Release Note**

```release-note
CronJobSource now comes from installing eventing.
```

### CODE REVIEW

**Comment by n3wscott** [comment]
/hold 
until knative/eventing#1092 lands

**Comment by matzew** [comment]
@n3wscott this should go too: 

https://github.com/n3wscott/eventing-sources/tree/delete_moved_cron/samples/cronjob-source

**Comment by n3wscott** [comment]
The samples will be moved to Docs.

**Comment by matzew** [comment]
/lgtm

:smile:

**Comment by n3wscott** [comment]
knative/eventing#1092 landed

/hold cancel

**Comment by n3wscott** [comment]
Related to https://github.com/knative/docs/issues/1235

**Pull request merged**
