### PR TITLE
Use gke istio add-on.

### PR DESCRIPTION
**Pull request by n3wscott**
Do not depend on serving istio.

### CODE REVIEW

**Comment by adrcunha** [comment]
This PR shouldn't be necessary anymore, plus it would break local testing with non-GKE clusters. Updating test-infra to the latest version should be enough; @chaodaig and @Fredy-Z to confirm.

/hold

**Comment by chaodaiG** [comment]
> This PR shouldn't be necessary anymore, plus it would break local testing with non-GKE clusters. Updating test-infra to the latest version should be enough; @chaodaiG and @Fredy-Z to confirm.
> 
> /hold

agree

**Pull request closed without merging**
