### PR TITLE
Remove message dumper.

### PR DESCRIPTION
**Pull request by n3wscott**
Breaks the release.

### CODE REVIEW

**Comment by vaikas-google** [comment]
This is only from the release, perhaps update the subject of the PR to reflect that. If our eventual plan is to remove in favor of something else for example, we probably still have a ton of documentation that needs to be updated.

**Comment by grantr** [comment]
I believe that already occurred in https://github.com/knative/eventing-sources/pull/249. This is just fixing the release to not try building a missing artifact.

**Comment by n3wscott** [comment]
> This is only from the release, perhaps update the subject of the PR to reflect that. If our eventual plan is to remove in favor of something else for example, we probably still have a ton of documentation that needs to be updated.

It turns out this was fixing a bad merge: https://github.com/knative/eventing-sources/pull/264/files#diff-cede583a27c227d458ca67079957c8a2R27

**Pull request merged**
