### PR TITLE
Fix the 0.5 release CI flow issue

### PR DESCRIPTION
**Pull request by Fredy-Z**
The same fix as https://github.com/knative/eventing/pull/1253

**Release Note**

```release-note
NONE
```

### CODE REVIEW

**Comment by evankanderson** [comment]
Integration tests have a panic and some other stuff that doesn't look right...

**Comment by adrcunha** [comment]
Wow, kubectl panicking! :)
Let's see if it's just a weird transient thing...

/retest

**Comment by adrcunha** [comment]
/hold

This is unnecessarily importing tools/devstats. Let me fix test-infra first.

**Comment by adrcunha** [comment]
@Fredy-Z once https://github.com/knative/test-infra/pull/819 is merged, please update test-infra again and make sure nothing from `tools/devstats` remains.

**Comment by Fredy-Z** [comment]
It is a problem of test-infra. Use https://github.com/knative/test-infra/issues/723 to track this issue, so close this PR for now.

**Pull request closed without merging**
