### PR TITLE
Update dep for test-infra

### PR DESCRIPTION
**Pull request by nbarthwal**
## Proposed Changes

  * Updating test-infra dependency of vendor using dep update

### CODE REVIEW

**Comment by adrcunha** [comment]
This is doing more than it should: 190 changed files.

/hold

**Comment by adrcunha** [comment]
> /retest

This won't work, this update is wrong. Your Gopkg file has 100+ changes, when it's expected that only 2 lines change (only test-infra).

**Comment by nbarthwal** [comment]
This is faulty, will send a new PR!

**Pull request closed without merging**
