### PR TITLE
Bind Kafka and Camel sources to the addressable-resolver role.

### PR DESCRIPTION
**Pull request by Harwayne**
## Proposed Changes

  * Bind Kafka and Camel sources to the addressable-resolver role.

**Release Note**

```release-note
KafkaSource can use Broker as a sink.
```

### CODE REVIEW

**Comment by Harwayne** [comment]
I tested:

KafkaSource by `ko apply -f contrib/kafka/config/`, and creating a KafkaSource. It was marked ready. It looked like it would work, but I didn't actually have Kafka running, so the receive-adapter pod errored (`panic: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)`).

CamelSource I haven't tested because I don't have the Camel operator installed. I `ko apply -f contrib/camel/config/` and it worked, but the controller dies quickly because Camel isn't installed (`no matches for kind "Integration" in version "camel.apache.org/v1alpha1"`).

**Comment by matzew** [comment]
:eyes:

**Comment by matzew** [comment]
got this, on my `event-display`

```
☁️  cloudevents.Event
Validation: valid
Context Attributes,
  specversion: 0.2
  type: dev.knative.kafka.event
  source: my-topic
  id: partition:0/offset:793
  time: 2019-05-03T15:59:34.5349841Z
  contenttype: application/json
Extensions,
  key: 
Data,
  {
    "data": {
      "brokerage": {
        "broker": {
          "id": "BMS-USB-5-JACE",
          "meta": {
            "building": "Urban Sciences Building",
            "buildingFloor": "5",
            "protocol": "BACNET"
          }
        },
        "id": "Drivers.L6_C2_Electric_Meters.C2_Mechcanical_Plant.points.C2_HTG_Pump_Current",
        "meta": {}
      },
      "entity": {
...
```

**Comment by matzew** [comment]
@Harwayne I think the `201-clusterrole` conflicts, due to the recent changes w/ the registry

**Comment by Harwayne** [comment]
> @Harwayne I think the `201-clusterrole` conflicts, due to the recent changes w/ the registry

Done.

**Pull request merged**
