### PR TITLE
Add gitlab source

### PR DESCRIPTION
**Pull request by vincent-pli**
## Proposed Changes
Add Gitlab as a build in source

Add new CRD: GitLabSource and related controller

Thanks

### CODE REVIEW

**Comment by evankanderson** [comment]
I believe that we're trying to separate these into separate directories under `contrib/` for better packaging.

Do you mind moving this in that direction?

**Comment by vincent-pli** [comment]
@evankanderson thanks.
Sure, I can move these stuff to `contrib/`
just little confuse, I guess the "gitlab" stuff is almost the same thing with "github" stuff, do we have plan to move "github" to `contrib/`🤔

**Comment by grantr** [comment]
> just little confuse, I guess the "gitlab" stuff is almost the same thing with "github" stuff, do we have plan to move "github" to `contrib/`🤔

Good question! My understanding is that GitHubSource will also move to contrib.

**Comment by vincent-pli** [comment]
@grantr thanks for your clarification, I will close this PR then move these stuff to `/contrib`

**Pull request closed without merging**
