### PR TITLE
Add check_suite events added to githubsource types

### PR DESCRIPTION
**Pull request by iancoffey**
## Proposed Changes

Adds handling for check_suite events from github events API. This involved updating to GH API v3->v5.

```release-note

None
```

### CODE REVIEW

**Comment by sebgoa** [comment]
Ideally we should add a test in https://github.com/knative/eventing-sources/blob/master/pkg/adapter/github/adapter_test.go

/ok-to-test

**Comment by matzew** [comment]
+1 on adding a test for that

**Comment by iancoffey** [comment]
Indeed, will add tests, ty!

**Comment by iancoffey** [comment]
So this PR grew quite a bit - it turns the GH v3 api does not support `check_suite` events, so I upgraded this project to use Gh events v5.

Now, it supports check suites and has a test as well 😄

**Comment by matzew** [comment]
Release notes ?   regarding the version upgrade ?

**Pull request merged**
