### PR TITLE
Delete KubernetesEventSource, replaced by ApiServerSource

### PR DESCRIPTION
**Pull request by n3wscott**
## Proposed Changes

  * Remove KubernetesEventSource, replaced by ApiServerSource

**Release Note**

```release-note
KubernetesEventSource will no longer ship with eventing-sources. Migrate to ApiServerSource found in knative/eventing.
```

follow-up to https://github.com/knative/eventing/pull/1175

### CODE REVIEW

**Comment by n3wscott** [comment]
/hold
until https://github.com/knative/eventing/pull/1175 lands

**Comment by n3wscott** [comment]
Istio still having a bad day over here.

/retest

**Comment by n3wscott** [comment]
/hold cancel

This is now ready.

**Comment by vaikas-google** [comment]
Can you also link a corresponding issue / PR for the documentations website?

**Comment by n3wscott** [comment]
This one: https://github.com/knative/docs/issues/1301

**Pull request merged**
