### PR TITLE
awssqs: fix breakage after moving to contrib/

### PR DESCRIPTION
**Pull request by srvaroa**
Fixes two issues introduced at f62c2387. (See https://github.com/knative/eventing-sources/pull/253)

### CODE REVIEW

**Comment by srvaroa** [comment]
NOTE: I have not yet verified this on a running cluster.

**Comment by nachocano** [comment]
great!!! Thanks @srvaroa 
/lgtm

**Comment by srvaroa** [comment]
Confirmed to be working with eventing-sources @0451142c and eventing @53ee52c1 

Note that it'll fail with v0.5 due to "no matches for kind "EventType" in version "eventing.knative.dev/v1alpha1" as it needs the dependency on eventing v0.6.

**Comment by nachocano** [comment]
/assign @n3wscott
This one also needs to be merged before the 0.6 cut. Thanks!

**Pull request merged**
