### PR TITLE
Setup the Container Source spec and status object.

### PR DESCRIPTION
**Pull request by n3wscott**
## Proposed Changes

  * Adding ContainerSource spec and status

**Release Note**
```release-note
NONE
```

### CODE REVIEW

**Comment by adrcunha** [comment]
I think there's something wrong here...
a) This is a 7000+ file PR.
b) It's so large that GitHub only displays the first 3000 files for review.
c) There's a merge conflict.
d) I see stuff copied from knative/eventing, like the `hack` directory, which I fail to link to the PR title and description.

**Comment by n3wscott** [comment]
@adrcunha yeah I think I had an issue where my master and this remote was detached. I think I have fixed it...

**Comment by adrcunha** [comment]
Thanbks! Then there's nothing for me to review here now. :D

**Comment by n3wscott** [comment]
Please look at https://github.com/knative/eventing-sources/pull/6/files#diff-b0a4c039a9ff9f0858ed28a74e82e0a3
and https://github.com/knative/eventing-sources/pull/6/files#diff-b9a5df0964d4f7d4a3aebd5503a9c156

**Comment by n3wscott** [comment]
revert if issues. moving on.

**Pull request merged**
