### PR TITLE
fix compilation of gcppubsub adapter test

### PR DESCRIPTION
**Pull request by dprotaso**

### CODE REVIEW

**Comment by Harwayne** [comment]
/lgtm

Looks like it was broken by #166. How did prow let it in? Does prow not check things in `contrib/`?

**Comment by dprotaso** [comment]
> /lgtm
> 
> Looks like it was broken by #166. How did prow let it in? Does prow not check things in `contrib/`?

Yeah looks like only things instead `pkg` and `cmd` are unit tested
https://github.com/knative/eventing-sources/blob/master/test/presubmit-tests.sh#L27

**Comment by grantr** [comment]
Does this need to be in the 0.3 release?

**Comment by grantr** [comment]
Answer: no because it's tests only.

**Pull request merged**
